version: "3.9" # Especifica a versão do formato do arquivo Docker Compose

services: # Define os serviços que compõem a aplicação
  # Serviço: big-bear-speedtest-tracker
  speedtest:
    image: linuxserver/speedtest-tracker:0.20.7 # Imagem Docker a ser usada, puxando a última versão
    ports:
      - "1580:80" # Mapeia a porta 1580 no host para a porta 80 no contêiner; usada para tráfego HTTP
      - "1543:443" # Mapeia a porta 1543 no host para a porta 443 no contêiner; usada para tráfego HTTPS
    environment: # Variáveis de ambiente para o contêiner, usadas para configurar o software do contêiner
      - PUID=1000 # ID do usuário para permissões de arquivo
      - PGID=1000 # ID do grupo para permissões de arquivo
      - DB_CONNECTION=mysql # Tipo de conexão de banco de dados, indicando que MySQL é usado
      - DB_HOST=speedtest-db # Nome do host do banco de dados, vinculado ao serviço db
      - DB_PORT=3306 # Porta para o banco de dados MySQL
      - DB_DATABASE=speedtest_tracker # Nome do banco de dados a ser usado
      - DB_USERNAME=dockge # Nome de usuário do banco de dados
      - DB_PASSWORD=dockge # Senha do banco de dados
      - TZ=UTC # Configuração de fuso horário para o contêiner; afeta como o tempo é relatado
    volumes: # Monta caminhos do host no contêiner, para armazenamento persistente ou compartilhamento de dados
      - "/etc/localtime:/etc/localtime:ro" # Monta o localtime do host como somente leitura para sincronização precisa do tempo
      - "speedtest_tracker_config:/config" # Volume para armazenamento de arquivos de configuração
      - "speedtest_tracker_web:/etc/ssl/web" # Volume para armazenamento de certificados SSL ou arquivos relacionados à web
    deploy:
      restart_policy:
        condition: any
    networks:
      - speedtest_network # Anexa o contêiner à rede speedtest_network
    depends_on: # Configuração de dependência, indicando que este serviço depende do serviço db
      - speedtest-db # Garante que o serviço db seja iniciado antes do speedtest-tracker
        
  # Serviço: db (Banco de Dados)
  speedtest-db:
    image: mariadb:10 # Imagem MariaDB, versão 10, usada como servidor de banco de dados
    environment: # Variáveis de ambiente para configurar o MariaDB
      - MARIADB_DATABASE=speedtest_tracker # Banco de dados a ser criado automaticamente
      - MARIADB_USER=dockge # Nome de usuário para o banco de dados, usado pelo speedtest-tracker
      - MARIADB_PASSWORD=dockge # Senha para o usuário do banco de dados
      - MARIADB_RANDOM_ROOT_PASSWORD=true # Habilita a geração de senha aleatória para o usuário root para segurança
    networks:
      - speedtest_network # Anexa o contêiner à rede speedtest_network
    volumes: # Monta para armazenamento de banco de dados, garantindo que os dados persistam entre reinicializações e remoções de contêiner
      - speedtest_tracker_db:/var/lib/mysql # Mapeia o diretório do host para o local de armazenamento do banco de dados do contêiner
    deploy:
      restart_policy:
        condition: any  
        
# Define a configuração das redes
networks:
  speedtest_network:
    external: true # Especifica que a rede já existe fora do escopo do Compose

volumes:
  speedtest_tracker_config: # Volume nomeado para armazenamento de arquivos de configuração
    driver: local # Gerenciado pelo driver de volume local do Docker
  speedtest_tracker_web: # Volume nomeado para armazenamento de certificados SSL ou arquivos relacionados à web
    driver: local # Gerenciado pelo driver de volume local do Docker
  speedtest_tracker_db: # Volume nomeado para armazenamento do banco de dados
    driver: local # Gerenciado pelo driver de volume local do Docker
